#!/usr/bin/env python3
"""Generate sitemap.xml for neilkodner.com from catalog.json.

Stdlib only (Python 3.11). Run from the repo root:

    python scripts/build_seo.py

Reads catalog.json (repo root) and writes sitemap.xml (repo root). Output is
deterministic so it doesn't churn the git diff when the catalog is unchanged.
"""

import json
import os
import re
import sys
from urllib.parse import quote
from xml.sax.saxutils import escape


def media_url(base, path):
    """Join an R2 base origin and an object path into a fetchable URL,
    percent-encoding path segments (R2 keys can contain spaces, e.g.
    "USAF Thunderbirds/img.jpg") so scrapers and sitemaps resolve them."""
    return f"{base.rstrip('/')}/{quote(str(path).lstrip('/'), safe='/')}"

SITE_ORIGIN = "https://neilkodner.com"

# Resolve paths relative to the repo root (parent of this script's directory)
# so the script works whether invoked from the repo root or elsewhere.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOG_PATH = os.path.join(REPO_ROOT, "catalog.json")
SITEMAP_PATH = os.path.join(REPO_ROOT, "sitemap.xml")
INDEX_PATH = os.path.join(REPO_ROOT, "index.html")

# Markers in index.html between which the og:image tag is rewritten. The
# content between them is fully replaced each run so it stays in sync with the
# first hero image and never duplicates on repeated runs.
OG_IMAGE_START = "<!-- og:image:start (auto-generated by scripts/build_seo.py — do not edit) -->"
OG_IMAGE_END = "<!-- og:image:end -->"


def normalize_lastmod(date):
    """Return a valid W3C date (YYYY or YYYY-MM) from an album date, or None.

    Album dates look like "2024-07" or "2024". Anything that doesn't match a
    plausible year / year-month is dropped rather than emitting invalid XML.
    """
    if not date:
        return None
    date = str(date).strip()
    if re.fullmatch(r"\d{4}", date):
        return date
    m = re.fullmatch(r"(\d{4})-(\d{2})", date)
    if m:
        month = int(m.group(2))
        if 1 <= month <= 12:
            return date
    # Try to salvage a YYYY-MM-DD style value as YYYY-MM.
    m = re.fullmatch(r"(\d{4})-(\d{2})-\d{2}", date)
    if m and 1 <= int(m.group(2)) <= 12:
        return f"{m.group(1)}-{m.group(2)}"
    return None


def url_entry(loc, lastmod=None, images=None):
    """Build a <url> element as a list of indented string lines."""
    lines = ["  <url>", f"    <loc>{escape(loc)}</loc>"]
    if lastmod:
        lines.append(f"    <lastmod>{escape(lastmod)}</lastmod>")
    for img_loc, caption in images or []:
        lines.append("    <image:image>")
        lines.append(f"      <image:loc>{escape(img_loc)}</image:loc>")
        if caption:
            lines.append(f"      <image:caption>{escape(caption)}</image:caption>")
        lines.append("    </image:image>")
    lines.append("  </url>")
    return lines


def og_image_url(catalog):
    """Resolve the og:image URL from the first hero image, or None.

    Prefers hero[0].resized (a path like "_resized/hero/<file>") when present,
    else falls back to "_hero/<filename>". Both are joined to the catalog's
    baseUrl (the R2 origin). Returns None when there is no usable hero image.
    """
    base_url = catalog.get("baseUrl", "").rstrip("/")
    hero = catalog.get("hero") or []
    if not base_url or not hero:
        return None

    first = hero[0]
    resized = first.get("resized")
    if resized:
        path = str(resized).lstrip("/")
    else:
        filename = first.get("filename")
        if not filename:
            return None
        path = f"_hero/{filename}"
    return media_url(base_url, path)


def update_og_image(catalog):
    """Rewrite the og:image meta tag in index.html between the markers.

    Idempotent: replaces only the content between OG_IMAGE_START/OG_IMAGE_END,
    so repeated runs don't duplicate tags and produce no diff when unchanged.
    Leaves the file untouched (placeholder intact) when there's no hero image
    or the markers are missing.
    """
    url = og_image_url(catalog)
    if not url:
        print("No hero image in catalog — leaving og:image placeholder.")
        return

    try:
        with open(INDEX_PATH, encoding="utf-8") as f:
            html = f.read()
    except FileNotFoundError:
        print(f"{INDEX_PATH} not found — skipping og:image update.")
        return

    pattern = re.compile(
        re.escape(OG_IMAGE_START) + r".*?" + re.escape(OG_IMAGE_END),
        re.DOTALL,
    )
    replacement = (
        f"{OG_IMAGE_START}\n"
        f'  <meta property="og:image"       content="{escape(url, {chr(34): "&quot;"})}">\n'
        f"  {OG_IMAGE_END}"
    )
    new_html, count = pattern.subn(lambda _m: replacement, html, count=1)
    if count == 0:
        print("og:image markers not found in index.html — skipping.")
        return

    if new_html != html:
        with open(INDEX_PATH, "w", encoding="utf-8") as f:
            f.write(new_html)
        print(f"Set og:image in index.html: {url}")
    else:
        print(f"og:image already up to date: {url}")


# ── Static per-album pages (pretty canonical URLs) ──────────────────────────

PHOTOGRAPHY_DIR = os.path.join(REPO_ROOT, "photography")
# Identifies files this script generates, so cleanup never touches the
# hand-written photography/index.html or anything else.
STUB_MARKER = "<!-- generated-album-stub -->"

_MONTHS = ["January", "February", "March", "April", "May", "June", "July",
           "August", "September", "October", "November", "December"]


def slugify(value):
    """Lowercase; every run of non-alphanumeric chars → a single hyphen; trim.

    CONTRACT: must match slugify() in js/app.js (and the inline slug() in
    album.html) so generated directory names line up with the hrefs the
    frontend builds. "USAF Thunderbirds" → "usaf-thunderbirds".
    """
    return re.sub(r"[^a-z0-9]+", "-", str(value).lower()).strip("-")


def album_pretty_path(cat_id, album_id):
    """Canonical album URL path: /photography/<cat-slug>/<album-slug>/"""
    return f"/photography/{slugify(cat_id)}/{slugify(album_id)}/"


def _attr(value):
    """Escape a string for use inside an HTML double-quoted attribute."""
    return escape(str(value), {'"': "&quot;"})


def _format_date(value):
    """'2024-07' → 'July 2024', '2024' → '2024' (mirrors app.js formatDate)."""
    if not value:
        return ""
    parts = str(value).split("-")
    year = parts[0]
    if len(parts) < 2:
        return year
    try:
        month = int(parts[1])
        if 1 <= month <= 12:
            return f"{_MONTHS[month - 1]} {year}"
    except ValueError:
        pass
    return year


def album_og_image(catalog, album):
    """Best og:image for an album: the cover, else the first photo's largest
    resized variant (a ~2000px JPEG — safely under social size limits), else
    the first photo full-res, else the site hero."""
    base = catalog.get("baseUrl", "").rstrip("/")
    if not base:
        return og_image_url(catalog)

    cover = album.get("cover")
    if cover:
        return media_url(base, cover)

    photos = album.get("photos") or []
    if photos:
        first = photos[0]
        sizes = first.get("sizes") or []
        if sizes:
            return media_url(base, sizes[-1].get("path", ""))
        filename = first.get("filename")
        if filename:
            return media_url(base, f"{album.get('folder', '')}/{filename}")

    return og_image_url(catalog)


def render_album_stub(catalog, cat, album):
    """Return the full HTML for a static per-album page.

    The head carries real og/Twitter/JSON-LD metadata (so scrapers get a
    preview); the body mirrors the legacy album.html shell and boots gallery.js
    with the album's real cat/album ids.
    """
    base = catalog.get("baseUrl", "").rstrip("/")
    cat_id = cat.get("id")
    album_id = album.get("id")
    folder = album.get("folder", "")
    page_url = f"{SITE_ORIGIN}{album_pretty_path(cat_id, album_id)}"

    title = (cat.get("name") if cat.get("flat") else album.get("title")) or album_id
    location = album.get("location") or ""
    description = f"{title} — photography by Neil Kodner."
    if location:
        description = f"{title} — photography by Neil Kodner. {location}."

    meta_bits = [b for b in (_format_date(album.get("date")), location) if b]
    meta_line = " · ".join(meta_bits)
    cat_name = cat.get("name") or cat_id
    og_image = album_og_image(catalog, album) or ""

    # JSON-LD ImageGallery.
    image_urls = [
        media_url(base, f"{folder}/{p['filename']}")
        for p in album.get("photos", []) if p.get("filename")
    ]
    ld = {
        "@context": "https://schema.org",
        "@type": "ImageGallery",
        "name": title,
        "url": page_url,
        "description": description,
        "author": {"@type": "Person", "name": "Neil Kodner"},
    }
    if og_image:
        ld["image"] = og_image
    if image_urls:
        ld["associatedMedia"] = [
            {"@type": "ImageObject", "contentUrl": u} for u in image_urls[:50]
        ]
    json_ld = json.dumps(ld, ensure_ascii=False, indent=2).replace("<", "\\u003c")

    image_tags = ""
    if og_image:
        image_tags = (
            f'  <meta property="og:image"       content="{_attr(og_image)}">\n'
            f'  <meta name="twitter:image"      content="{_attr(og_image)}">\n'
        )

    preconnect = ""
    if base:
        preconnect = (
            f'  <link rel="preconnect" href="{_attr(base)}" crossorigin>\n'
            f'  <link rel="dns-prefetch" href="{_attr(base)}">\n'
        )

    cat_json = json.dumps(cat_id, ensure_ascii=False)
    album_json = json.dumps(album_id, ensure_ascii=False)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  {STUB_MARKER}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="color-scheme" content="light">

{preconnect}
  <title>{escape(title)} — Neil Kodner</title>
  <meta name="description" content="{_attr(description)}">
  <link rel="canonical" href="{_attr(page_url)}">

  <meta property="og:type"        content="website">
  <meta property="og:url"         content="{_attr(page_url)}">
  <meta property="og:title"       content="{_attr(title)} — Neil Kodner">
  <meta property="og:description" content="{_attr(description)}">
  <meta property="og:site_name"   content="Photography by Neil Kodner">
  <meta name="twitter:card"       content="summary_large_image">
  <meta name="twitter:title"      content="{_attr(title)} — Neil Kodner">
  <meta name="twitter:description" content="{_attr(description)}">
{image_tags}
  <script type="application/ld+json">
{json_ld}
  </script>

  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  <link rel="preload" href="/fonts/space-grotesk-latin.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="/css/tokens.css">
  <link rel="stylesheet" href="/css/style.css">
  <link rel="stylesheet" href="/css/print.css" media="print">
  <link rel="stylesheet" href="/vendor/photoswipe/photoswipe.css">
  <link rel="stylesheet" href="/css/lightbox.css">
</head>
<body>

  <a href="#main-content" class="skip-link">Skip to content</a>

  <nav class="site-nav" aria-label="Primary">
    <div class="container">
      <a href="/" class="nav-brand">Photography by Neil Kodner</a>
      <ul class="nav-links" role="list">
        <li><a href="/">Home</a></li>
        <li><a href="/photography/" aria-current="page">Photography</a></li>
        <li><a href="/about/">About</a></li>
      </ul>
    </div>
  </nav>
  <div class="nav-offset" aria-hidden="true"></div>

  <main id="main-content">
    <div class="container">

      <nav class="album-breadcrumb" aria-label="Breadcrumb" style="padding-block:var(--space-6) 0">
        <ol style="display:flex;gap:var(--space-2);list-style:none;font-size:var(--text-xs);letter-spacing:0.06em;color:var(--color-text-muted)">
          <li><a href="/photography/">Photography</a></li>
          <li aria-hidden="true" style="opacity:0.4">/</li>
          <li><a id="breadcrumb-cat" href="/photography/?cat={escape(str(cat_id))}">{escape(str(cat_name))}</a></li>
          <li aria-hidden="true" style="opacity:0.4">/</li>
          <li style="color:var(--color-text)" aria-current="page" id="album-title-crumb">{escape(title)}</li>
        </ol>
      </nav>

      <header class="page-header" style="margin-top:var(--space-4)">
        <h1 id="album-title">{escape(title)}</h1>
        <p id="album-meta" class="label" style="margin-top:var(--space-2)">{escape(meta_line)}</p>
      </header>

      <p id="album-loading" style="color:var(--color-text-muted);padding-block:var(--space-8)">Loading photos…</p>
      <p id="album-error" hidden style="color:var(--color-text-muted);padding-block:var(--space-8)">Could not load album.</p>

      <div class="album-grid" id="photo-grid" style="padding-bottom:var(--space-16)"></div>

    </div>
  </main>

  <footer class="site-footer">
    <div class="container">
      <p>&copy; 2026 Neil Kodner</p>
    </div>
  </footer>

  <script type="module">
    import {{ renderAlbumPage }} from '/js/gallery.js';
    renderAlbumPage({cat_json}, {album_json});
  </script>

</body>
</html>
"""


def _write_if_changed(path, content):
    """Write content only when it differs — keeps the git diff quiet."""
    try:
        with open(path, encoding="utf-8") as f:
            if f.read() == content:
                return False
    except FileNotFoundError:
        pass
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return True


def write_album_pages(catalog):
    """Generate /photography/<cat>/<album>/index.html for every album and prune
    generated stubs for albums that no longer exist. Returns the page count."""
    generated = set()
    count = 0
    for cat in catalog.get("categories", []):
        cat_id = cat.get("id")
        if cat_id is None:
            continue
        for album in cat.get("albums", []):
            album_id = album.get("id")
            if album_id is None:
                continue
            cat_slug, album_slug = slugify(cat_id), slugify(album_id)
            out_dir = os.path.join(PHOTOGRAPHY_DIR, cat_slug, album_slug)
            os.makedirs(out_dir, exist_ok=True)
            _write_if_changed(
                os.path.join(out_dir, "index.html"),
                render_album_stub(catalog, cat, album),
            )
            generated.add((cat_slug, album_slug))
            count += 1

    # Prune stale generated stubs (album renamed/removed). Only delete files
    # that carry STUB_MARKER, so the hand-written photography/index.html and
    # any non-generated content are always safe.
    if os.path.isdir(PHOTOGRAPHY_DIR):
        for cat_slug in os.listdir(PHOTOGRAPHY_DIR):
            cat_dir = os.path.join(PHOTOGRAPHY_DIR, cat_slug)
            if not os.path.isdir(cat_dir):
                continue
            for album_slug in os.listdir(cat_dir):
                album_dir = os.path.join(cat_dir, album_slug)
                index = os.path.join(album_dir, "index.html")
                if (cat_slug, album_slug) in generated or not os.path.isfile(index):
                    continue
                with open(index, encoding="utf-8") as f:
                    if STUB_MARKER not in f.read(2048):
                        continue
                os.remove(index)
                try:
                    os.rmdir(album_dir)
                except OSError:
                    pass
            try:
                os.rmdir(cat_dir)  # remove now-empty category dir
            except OSError:
                pass

    return count


def main():
    with open(CATALOG_PATH, encoding="utf-8") as f:
        catalog = json.load(f)

    base_url = catalog.get("baseUrl", "").rstrip("/")
    categories = catalog.get("categories", [])

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"'
        ' xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">',
    ]

    url_count = 0
    image_count = 0

    # Static pages.
    for path in ("/", "/photography/", "/about/"):
        lines += url_entry(f"{SITE_ORIGIN}{path}")
        url_count += 1

    # Category and album pages (stable ordering: as listed in catalog.json).
    for cat in categories:
        cat_id = cat.get("id")
        if cat_id is None:
            continue

        # Category index page — skipped for flat categories (they link
        # straight to an album, so there is no standalone category page).
        if not cat.get("flat"):
            loc = f"{SITE_ORIGIN}/photography/?cat={cat_id}"
            lines += url_entry(loc)
            url_count += 1

        for album in cat.get("albums", []):
            album_id = album.get("id")
            folder = album.get("folder", "")
            if album_id is None:
                continue

            loc = f"{SITE_ORIGIN}{album_pretty_path(cat_id, album_id)}"
            lastmod = normalize_lastmod(album.get("date"))

            images = []
            for photo in album.get("photos", []):
                filename = photo.get("filename")
                if not filename:
                    continue
                img_loc = media_url(base_url, f"{folder}/{filename}")
                images.append((img_loc, photo.get("caption") or None))
                image_count += 1

            lines += url_entry(loc, lastmod=lastmod, images=images)
            url_count += 1

    lines.append("</urlset>")
    lines.append("")  # trailing newline

    with open(SITEMAP_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(
        f"Wrote {SITEMAP_PATH}: {url_count} URLs, {image_count} image entries.",
        file=sys.stdout,
    )

    update_og_image(catalog)

    pages = write_album_pages(catalog)
    print(f"Generated {pages} static per-album pages under photography/.")


if __name__ == "__main__":
    main()
