#!/bin/bash
#
# upload-to-r2.sh — sync ~/Pictures/neilkodner.com to Cloudflare R2
#
# Behavior: rclone sync — R2 mirrors local exactly.
#   New/changed files are uploaded. Files deleted locally are deleted from R2.
#   _thumbs/ is always excluded (auto-generated by GitHub Actions).
#
# First-time setup:
#   1. Run: rclone config
#   2. Choose "n" (new remote), name it "r2-neilkodner"
#   3. Type: s3
#   4. Provider: Cloudflare
#   5. env_auth: false
#   6. Paste your R2 Access Key ID and Secret Access Key
#   7. Endpoint: https://<account_id>.r2.cloudflarestorage.com
#      (find Account ID on the Cloudflare R2 overview page)
#   8. Leave all other settings blank/default
#
# Usage:
#   ./scripts/upload-to-r2.sh           # live sync
#   ./scripts/upload-to-r2.sh --dry-run # preview what would change

set -euo pipefail

REMOTE="r2-neilkodner"
BUCKET="neilkodner-photos"
LOCAL="$HOME/Pictures/neilkodner.com"

# Verify rclone remote exists
if ! rclone listremotes | grep -q "^${REMOTE}:"; then
  echo "ERROR: rclone remote '${REMOTE}' not found."
  echo ""
  echo "Run 'rclone config' and create a remote named '${REMOTE}'."
  echo "See the setup instructions at the top of this script."
  exit 1
fi

# Verify local source exists
if [ ! -d "$LOCAL" ]; then
  echo "ERROR: Local folder not found: $LOCAL"
  exit 1
fi

DRY_RUN=""
if [ "${1:-}" = "--dry-run" ]; then
  DRY_RUN="--dry-run"
  echo "=== DRY RUN — no files will be changed ==="
fi

echo "Syncing $LOCAL → ${REMOTE}:${BUCKET}"
echo ""

rclone sync "$LOCAL" "${REMOTE}:${BUCKET}" \
  --exclude "_thumbs/**" \
  --progress \
  --transfers 8 \
  $DRY_RUN

echo ""
echo "Done."
